CREATE TABLE `tblofficerhistory` (
  `HISTORYID` int(11) NOT NULL,
  `OFFICERID` int(11) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `RECSTATUS` smallint(6) DEFAULT NULL,
  `LASTUPDATE` datetime DEFAULT NULL,
  `LASTUPTIME` mediumtext,
  `LASTUPUSERID` int(11) DEFAULT NULL,
  `ORIGINALID` int(11) DEFAULT NULL,
  `VERSIONID` int(11) DEFAULT NULL,
  PRIMARY KEY (`HISTORYID`),
  UNIQUE KEY `HISTORYID_UNIQUE` (`HISTORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SELECT * FROM pawn_archive.tblauctionticket;